# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for ReOrder (重序) v3.0"""

a = Analysis(
    ['ReOrder.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PIL',
        'PIL.ExifTags',
        'PIL._imagingtk',
        'PIL.ImageTk',
        'customtkinter',
        'mutagen',
        'mutagen.easyid3',
        'mutagen.mp3',
        'mutagen.flac',
        'mutagen.wavpack',
        'mutagen.oggvorbis',
        'mutagen.mp4',
        'hachoir',
        'hachoir.parser',
        'hachoir.metadata',
        'pypinyin',
        'pypinyin.pinyin_dict',
        'pypinyin.phonetic_symbol',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.colorchooser',
        'queue',
        'logging',
        'traceback',
        'tkinterdnd2',
        'tkinterdnd2.TkinterDnD',
        'json',
        'csv',
        'hashlib',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ReOrder',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
